---
- name: testing port 443 on server number 1 
  portcheck:
    name: portcheck
    ssl: yes
    target_port: 443
    protocol: tcp
    target_fqdn: test.example.com
    spearedge_fqdn: portcheck.example.com
    spearedge_path: spearedge
    openshift_node: worker1.example.com